NODE_RRF_K = 60
NODE_RRF_LIMIT_TOP = 5

# reranker 重排序处理参数
RERANKER_MAX_TOPK = 6
RERANKER_MIN_TOPK = 2
RERANKER_GAP_RATIO = 0.2
RERANKER_GAP_ABS = 0.2
RERANKER_MAX_INPUT_TOKENS = 512
RERANKER_SUMMARY_CHAR_RATIO = 1.3
RERANKER_MIN_SUMMARY_CHARS = 50

SUPPORTED_IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp")
